### PR TITLE
Adding an Option

### PR DESCRIPTION
**Pull request by mckaycr**
I was working with your module, really liked it.  My CSV uses pipes as a separator though, so I thought I might add some edits to your module to allow users to change this if they need.

### CODE REVIEW

**Comment by tleen** [comment]
Our module now! :smile: Thanks.

**Comment by tleen** [comment]
Tried this, had to reject, underlying CSV lib really takes the 'C' part literally, it allows no other delimiters. We could probably make this change, but it would require swapping out csv2array, or updating that module first.

**Comment by mckaycr** [comment]
Let me do some more testing.  I tried it several times with multiple separators without an issues.  I'll take another stab at it.  csv2array actually already accepts a separator option, so it was as simple as adding it to dbcsv, which forwards the option on to csv2array.  Shouldn't have been an issue.

**Comment by tleen** [comment]
Ok I see [it was undocumented](https://www.npmjs.com/package/csv2array). Just add a test case in test/index?

**Comment by tleen** [comment]
I added it back in + test. Actually looking at it, since separator is a pass through and already defaults to ',', the explicit setting of that in the defaults is unneccessary? Updated to v0.0.3 and published to npm.

**Comment by mckaycr** [comment]
Are you saying you don't have to add the option to dbcsv, because the option if used automatically passes through to csv2array?

**Comment by tleen** [comment]
Yes, I wrote the test before re-adding the separator and it worked because it passes through if you set it as an option. What do you think, should we enforce the separator at this module level (and make it explicit) or just let the csv2array handle it?

**Comment by mckaycr** [comment]
Let csv2array handle it. But keep it in the readme so that users know its an option without having to dig like I did.  Good stuff

**Comment by tleen** [comment]
Yep. All set, thanks for the update!

**Pull request merged**
